version: '3.8'
services:
  frontend:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - RUNNING_IN_DOCKER=true
      - PORT=${PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_URL=${BACKEND_URL}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
